### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by bedoya-daniel** [wergo/CEUS_Toolbox#1]
`t_t`
Found while executing `Demo01_openBoefile.m`

![Screenshot 2019-12-02 at 16 31 50](https://user-images.githubusercontent.com/33959228/69975507-a424bb80-1527-11ea-8f0b-80ce8b0e59c3.png)

**Comment by bedoya-daniel** [comment]
`crossing`
Found while executing `Demo01_openBoefile.m`
![Screenshot 2019-12-02 at 16 32 10](https://user-images.githubusercontent.com/33959228/69975870-4e9cde80-1528-11ea-8c7e-97d83d738f71.png)

**Comment by wergo** [comment]
Thanks for spotting this. Fixed with https://github.com/wergo/CEUS_Toolbox/commit/385cb31916299d24c61823b27770f2a3fd849329.
